server:
  port: 8080

spring:
  data:
    mongodb:
      uri: mongodb://13.209.68.198/VerificationManager
  jackson:
    property-naming-strategy: SNAKE_CASE
  kafka:
    bootstrap-servers: 13.209.68.198:9092
    consumer:
      group-id: team-vmc


logging:
  file:
    name: "/log/verification-manager.log"
  logback:
    rollingpolicy:
      max-file-size: 10MB
      total-size-cap: 100MB

cloud:
  aws:
    credentials:
      accessKey: AKIAX5JJUNOU6P4RFWUZ
      secretKey: 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
    s3:
      bucket: vmc-bucket
    region:
      static: ap-northeast-2
    stack:
      auto: false

verification:
  redirect-url: http://localhost:3000/CertificationUrl/