server:
  port: 8080

spring:
  data:
    mongodb:
      uri: mongodb://3.37.127.25/VerificationManager
  jackson:
    property-naming-strategy: SNAKE_CASE
  kafka:
    bootstrap-servers: 3.37.127.25:9092
    consumer:
      group-id: team-vmc

cloud:
  aws:
    credentials:
      accessKey: AKIAX5JJUNOU6P4RFWUZ
      secretKey: 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
    s3:
      bucket: vmc-bucket
    region:
      static: ap-northeast-2
    stack:
      auto: false

logging:
  file:
    name: "/log/verification-manager.log"
  logback:
    rollingpolicy:
      max-file-size: 10MB
      total-size-cap: 100MB

verification:
  redirect-url: http://vmc-front-prd.s3-website.ap-northeast-2.amazonaws.com/CertificationUrl/