server:
  port: 8081

spring:
  data:
    mongodb:
      uri: mongodb://13.209.68.198/VerificationManager
  jackson:
    property-naming-strategy: SNAKE_CASE
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    consumer:
      group-id: verification-group
      transaction-topic: transactionSummary
      user-topic: userManager.signOut

cloud:
  aws:
    credentials:
      accessKey: AKIAX5JJUNOU6P4RFWUZ
      secretKey: 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
    s3:
      bucket: vmc-bucket
    region:
      static: ap-northeast-2
    stack:
      auto: false


verification:
  redirect-url: http://localhost:3000/CertificationUrl/

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: ERROR