name: CI/CD on development branch

on:
  push:
    branches:
      - development

env:
  DOCKER_COMPOSE_SERVICE: verification-manager
  DOCKER_HUB_REPO: on91716/dev.verification-manager  # on91716/dev.${{ github.event.repository.name }}
  PROFILES: dev
  DESTINATION_SERVER: 3.37.123.157

jobs:
  ci_job:
    runs-on: ubuntu-latest
    steps:
    
    ########################## 1. For Docker build ##########################
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        target: development
        tags: |
          ${{ env.DOCKER_HUB_REPO }}:latest
          ${{ env.DOCKER_HUB_REPO }}:${{ github.sha }}
    ########################################################################

  cd_job:
    needs: ci_job
    runs-on: ubuntu-latest
    steps:
    ########################## 2. For SSH command ##########################
    - name: Checkout
      uses: actions/checkout@v2
      with:
        repository: TaemVMC/Builder

    - name: Set AWS Key
      run: 'echo "$EC2_PEM" > .vmc.pem && chmod 400 .vmc.pem'
      shell: bash
      env:
        EC2_PEM: ${{secrets.EC2_PEM}}

    - name: remove the specified number of leading path elements
      uses: appleboy/scp-action@master
      with:
        host: ${{ env.DESTINATION_SERVER }}
        username: ubuntu
        key_path: ".vmc.pem"
        source: "docker-compose.dev.yml"
        target: "./"

        
    - name: Update Docker compose
      uses: appleboy/ssh-action@master
      with:
        host: ${{ env.DESTINATION_SERVER }}
        username: ubuntu
        key_path: ".vmc.pem"
        script: |
           docker-compose -f docker-compose.dev.yml pull ${{ env.DOCKER_HUB_REPO }}
           SPRING_PROFILES_ACTIVE=${{ env.PROFILES }} docker-compose -f docker-compose.dev.yml up -d ${{env.DOCKER_COMPOSE_SERVICE}}
    ########################################################################
